# Generated by Django 4.0.2 on 2022-02-16 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='todolistItem',
        ),
    ]
