# Generated by Django 4.0.2 on 2022-02-16 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 16, 13, 23, 39, 570206)),
        ),
    ]
