# Generated by Django 4.0.2 on 2022-02-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_detail',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('emailid', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
