# Generated by Django 4.0.2 on 2022-02-19 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_detail_user_alter_user_detail_emailid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='password',
        ),
    ]
